# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_ts',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 5, 13, 10, 52, 84173, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_ts',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 5, 13, 11, 9, 490988, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
