# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160205_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='publication_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_ts',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
